/* Generated by           cobc 3.2.0 */
/* Generated from         <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/t3-binding-closure-v1/real-readiness-T3-BINDING-CLOSURE-V1/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cbl/CBACT04C.cbl */
/* Generated at           Sep 15 2026 16:31:01 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -std=ibm -fsign=ascii -I <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/t3-binding-closure-v1/real-readiness-T3-BINDING-CLOSURE-V1/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cpy -m -C -o <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/t3-binding-closure-v1/real-readiness-T3-BINDING-CLOSURE-V1/p2b-preparation/isolated-cycle/aws-carddemo-cycle-v1/P2b/build/CBACT04C.c <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/t3-binding-closure-v1/real-readiness-T3-BINDING-CLOSURE-V1/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cbl/CBACT04C.cbl */

/* Program local variables for 'CBACT04C' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d_0 = NULL;
cob_decimal	*d_1 = NULL;


/* File TCATBAL-FILE */
static cob_file_key	*k_TCATBAL_FILE = NULL;
static cob_file		*h_TCATBAL_FILE = NULL;
static unsigned char	h_TCATBAL_FILE_status[4];

/* File XREF-FILE */
static cob_file_key	*k_XREF_FILE = NULL;
static cob_file		*h_XREF_FILE = NULL;
static unsigned char	h_XREF_FILE_status[4];

/* File ACCOUNT-FILE */
static cob_file_key	*k_ACCOUNT_FILE = NULL;
static cob_file		*h_ACCOUNT_FILE = NULL;
static unsigned char	h_ACCOUNT_FILE_status[4];

/* File DISCGRP-FILE */
static cob_file_key	*k_DISCGRP_FILE = NULL;
static cob_file		*h_DISCGRP_FILE = NULL;
static unsigned char	h_DISCGRP_FILE_status[4];

/* File TRANSACT-FILE */
static cob_file		*h_TRANSACT_FILE = NULL;
static unsigned char	h_TRANSACT_FILE_status[4];

/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call pointers */
static cob_call_union	call_CEE3ABD;

/* Call parameters */
cob_field		*cob_procedure_params[2];

/* Perform frame stack */
struct cob_frame	*temp_index;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_23[50] __attribute__((aligned));	/* TCATBAL-FILE Record */
static cob_u8_t	b_29[50] __attribute__((aligned));	/* XREF-FILE Record */
static cob_u8_t	b_36[50] __attribute__((aligned));	/* DISCGRP-FILE Record */
static cob_u8_t	b_40[300] __attribute__((aligned));	/* ACCOUNT-FILE Record */
static cob_u8_t	b_44[350] __attribute__((aligned));	/* TRANSACT-FILE Record */
static cob_u8_t	b_45[50] __attribute__((aligned));	/* TRAN-CAT-BAL-RECORD */
static cob_u8_t	b_52[2] __attribute__((aligned));	/* TCATBALF-STATUS */
static cob_u8_t	b_55[50] __attribute__((aligned));	/* CARD-XREF-RECORD */
static cob_u8_t	b_60[2] __attribute__((aligned));	/* XREFFILE-STATUS */
static cob_u8_t	b_63[50] __attribute__((aligned));	/* DIS-GROUP-RECORD */
static cob_u8_t	b_70[2] __attribute__((aligned));	/* DISCGRP-STATUS */
static cob_u8_t	b_73[300] __attribute__((aligned));	/* ACCOUNT-RECORD */
static cob_u8_t	b_87[2] __attribute__((aligned));	/* ACCTFILE-STATUS */
static cob_u8_t	b_90[350] __attribute__((aligned));	/* TRAN-RECORD */
static cob_u8_t	b_105[2] __attribute__((aligned));	/* TRANFILE-STATUS */
static cob_u8_t	b_108[2] __attribute__((aligned));	/* IO-STATUS */
static cob_u8_t	b_111[2] __attribute__((aligned));	/* TWO-BYTES-BINARY */
static cob_u8_t	b_115[4] __attribute__((aligned));	/* IO-STATUS-04 */
static cob_u8_t	b_118[4] __attribute__((aligned));	/* APPL-RESULT */
static cob_u8_t	b_121[1] __attribute__((aligned));	/* END-OF-FILE */
static cob_u8_t	b_122[4] __attribute__((aligned));	/* ABCODE */
static cob_u8_t	b_123[4] __attribute__((aligned));	/* TIMING */
static cob_u8_t	b_124[21] __attribute__((aligned));	/* COBOL-TS */
static cob_u8_t	b_133[26] __attribute__((aligned));	/* DB2-FORMAT-TS */
static cob_u8_t	b_149[34] __attribute__((aligned));	/* WS-MISC-VARS */
static cob_u8_t	b_154[15] __attribute__((aligned));	/* WS-COUNTERS */

/* End of local data storage */


/* Fields (local) */
static cob_field f_18	= {17, b_23, &a_4};	/* FD-TRAN-CAT-KEY */
static cob_field f_23	= {50, b_23, &a_6};	/* TCATBAL-FILE Record */
static cob_field f_25	= {16, b_29, &a_6};	/* FD-XREF-CARD-NUM */
static cob_field f_27	= {11, b_29 + 25, &a_5};	/* FD-XREF-ACCT-ID */
static cob_field f_29	= {50, b_29, &a_6};	/* XREF-FILE Record */
static cob_field f_31	= {16, b_36, &a_4};	/* FD-DISCGRP-KEY */
static cob_field f_36	= {50, b_36, &a_6};	/* DISCGRP-FILE Record */
static cob_field f_37	= {300, b_40, &a_4};	/* FD-ACCTFILE-REC */
static cob_field f_38	= {11, b_40, &a_5};	/* FD-ACCT-ID */
static cob_field f_40	= {300, b_40, &a_6};	/* ACCOUNT-FILE Record */
static cob_field f_41	= {350, b_44, &a_4};	/* FD-TRANFILE-REC */
static cob_field f_44	= {350, b_44, &a_6};	/* TRANSACT-FILE Record */
static cob_field f_45	= {50, b_45, &a_4};	/* TRAN-CAT-BAL-RECORD */
static cob_field f_47	= {11, b_45, &a_5};	/* TRANCAT-ACCT-ID */
static cob_field f_50	= {11, b_45 + 17, &a_8};	/* TRAN-CAT-BAL */
static cob_field f_52	= {2, b_52, &a_4};	/* TCATBALF-STATUS */
static cob_field f_60	= {2, b_60, &a_4};	/* XREFFILE-STATUS */
static cob_field f_68	= {6, b_63 + 16, &a_9};	/* DIS-INT-RATE */
static cob_field f_70	= {2, b_70, &a_4};	/* DISCGRP-STATUS */
static cob_field f_74	= {11, b_73, &a_5};	/* ACCT-ID */
static cob_field f_76	= {12, b_73 + 12, &a_10};	/* ACCT-CURR-BAL */
static cob_field f_82	= {12, b_73 + 78, &a_10};	/* ACCT-CURR-CYC-CREDIT */
static cob_field f_83	= {12, b_73 + 90, &a_10};	/* ACCT-CURR-CYC-DEBIT */
static cob_field f_87	= {2, b_87, &a_4};	/* ACCTFILE-STATUS */
static cob_field f_91	= {16, b_90, &a_6};	/* TRAN-ID */
static cob_field f_95	= {100, b_90 + 32, &a_6};	/* TRAN-DESC */
static cob_field f_105	= {2, b_105, &a_4};	/* TRANFILE-STATUS */
static cob_field f_108	= {2, b_108, &a_4};	/* IO-STATUS */
static cob_field f_111	= {2, b_111, &a_14};	/* TWO-BYTES-BINARY */
static cob_field f_115	= {4, b_115, &a_4};	/* IO-STATUS-04 */
static cob_field f_117	= {3, b_115 + 1, &a_15};	/* IO-STATUS-0403 */
static cob_field f_122	= {4, b_122, &a_13};	/* ABCODE */
static cob_field f_123	= {4, b_123, &a_13};	/* TIMING */
static cob_field f_124	= {21, b_124, &a_4};	/* COBOL-TS */
static cob_field f_131	= {2, b_124 + 14, &a_6};	/* COB-MIL */
static cob_field f_147	= {2, b_133 + 20, &a_12};	/* DB2-MIL */
static cob_field f_150	= {11, b_149, &a_6};	/* WS-LAST-ACCT-NUM */
static cob_field f_151	= {11, b_149 + 11, &a_8};	/* WS-MONTHLY-INT */
static cob_field f_152	= {11, b_149 + 22, &a_8};	/* WS-TOTAL-INT */
static cob_field f_155	= {9, b_154, &a_3};	/* WS-RECORD-COUNT */
static cob_field f_156	= {6, b_154 + 9, &a_11};	/* WS-TRANID-SUFFIX */
static cob_field f_159	= {10, NULL, &a_6};	/* PARM-DATE */

/* End of fields */

