/* Generated by           cobc 3.2.0 */
/* Generated from         <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/t3-binding-closure-v1/real-readiness-T3-BINDING-CLOSURE-V1/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cbl/CBTRN02C.cbl */
/* Generated at           Sep 15 2026 16:31:00 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -std=ibm -fsign=ascii -I <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/t3-binding-closure-v1/real-readiness-T3-BINDING-CLOSURE-V1/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cpy -x -A -Dcob_write=p2b_observed_write -C -o <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/t3-binding-closure-v1/real-readiness-T3-BINDING-CLOSURE-V1/p2b-preparation/isolated-cycle/aws-carddemo-cycle-v1/P2b/build/CBTRN02C.c <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/t3-binding-closure-v1/real-readiness-T3-BINDING-CLOSURE-V1/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cbl/CBTRN02C.cbl */

/* Program local variables for 'CBTRN02C' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d_0 = NULL;
cob_decimal	*d_1 = NULL;


/* File DALYTRAN-FILE */
static cob_file		*h_DALYTRAN_FILE = NULL;
static unsigned char	h_DALYTRAN_FILE_status[4];

/* File TRANSACT-FILE */
static cob_file_key	*k_TRANSACT_FILE = NULL;
static cob_file		*h_TRANSACT_FILE = NULL;
static unsigned char	h_TRANSACT_FILE_status[4];

/* File XREF-FILE */
static cob_file_key	*k_XREF_FILE = NULL;
static cob_file		*h_XREF_FILE = NULL;
static unsigned char	h_XREF_FILE_status[4];

/* File DALYREJS-FILE */
static cob_file		*h_DALYREJS_FILE = NULL;
static unsigned char	h_DALYREJS_FILE_status[4];

/* File ACCOUNT-FILE */
static cob_file_key	*k_ACCOUNT_FILE = NULL;
static cob_file		*h_ACCOUNT_FILE = NULL;
static unsigned char	h_ACCOUNT_FILE_status[4];

/* File TCATBAL-FILE */
static cob_file_key	*k_TCATBAL_FILE = NULL;
static cob_file		*h_TCATBAL_FILE = NULL;
static unsigned char	h_TCATBAL_FILE_status[4];

/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call pointers */
static cob_call_union	call_CEE3ABD;

/* Call parameters */
cob_field		*cob_procedure_params[2];

/* Perform frame stack */
struct cob_frame	*temp_index;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_20[350] __attribute__((aligned));	/* DALYTRAN-FILE Record */
static cob_u8_t	b_24[350] __attribute__((aligned));	/* TRANSACT-FILE Record */
static cob_u8_t	b_28[50] __attribute__((aligned));	/* XREF-FILE Record */
static cob_u8_t	b_32[430] __attribute__((aligned));	/* DALYREJS-FILE Record */
static cob_u8_t	b_36[300] __attribute__((aligned));	/* ACCOUNT-FILE Record */
static cob_u8_t	b_43[50] __attribute__((aligned));	/* TCATBAL-FILE Record */
static cob_u8_t	b_44[350] __attribute__((aligned));	/* DALYTRAN-RECORD */
static cob_u8_t	b_59[2] __attribute__((aligned));	/* DALYTRAN-STATUS */
static cob_u8_t	b_62[350] __attribute__((aligned));	/* TRAN-RECORD */
static cob_u8_t	b_77[2] __attribute__((aligned));	/* TRANFILE-STATUS */
static cob_u8_t	b_80[50] __attribute__((aligned));	/* CARD-XREF-RECORD */
static cob_u8_t	b_85[2] __attribute__((aligned));	/* XREFFILE-STATUS */
static cob_u8_t	b_88[2] __attribute__((aligned));	/* DALYREJS-STATUS */
static cob_u8_t	b_91[300] __attribute__((aligned));	/* ACCOUNT-RECORD */
static cob_u8_t	b_105[2] __attribute__((aligned));	/* ACCTFILE-STATUS */
static cob_u8_t	b_108[50] __attribute__((aligned));	/* TRAN-CAT-BAL-RECORD */
static cob_u8_t	b_115[2] __attribute__((aligned));	/* TCATBALF-STATUS */
static cob_u8_t	b_118[2] __attribute__((aligned));	/* IO-STATUS */
static cob_u8_t	b_121[2] __attribute__((aligned));	/* TWO-BYTES-BINARY */
static cob_u8_t	b_125[4] __attribute__((aligned));	/* IO-STATUS-04 */
static cob_u8_t	b_128[4] __attribute__((aligned));	/* APPL-RESULT */
static cob_u8_t	b_131[1] __attribute__((aligned));	/* END-OF-FILE */
static cob_u8_t	b_132[4] __attribute__((aligned));	/* ABCODE */
static cob_u8_t	b_133[4] __attribute__((aligned));	/* TIMING */
static cob_u8_t	b_134[21] __attribute__((aligned));	/* COBOL-TS */
static cob_u8_t	b_143[26] __attribute__((aligned));	/* DB2-FORMAT-TS */
static cob_u8_t	b_159[430] __attribute__((aligned));	/* REJECT-RECORD */
static cob_u8_t	b_162[80] __attribute__((aligned));	/* WS-VALIDATION-TRAILER */
static cob_u8_t	b_165[29] __attribute__((aligned));	/* WS-COUNTERS */
static cob_u8_t	b_169[1] __attribute__((aligned));	/* WS-FLAGS */

/* End of local data storage */


/* Fields (local) */
static cob_field f_20	= {350, b_20, &a_4};	/* DALYTRAN-FILE Record */
static cob_field f_21	= {350, b_24, &a_3};	/* FD-TRANFILE-REC */
static cob_field f_22	= {16, b_24, &a_4};	/* FD-TRANS-ID */
static cob_field f_24	= {350, b_24, &a_4};	/* TRANSACT-FILE Record */
static cob_field f_26	= {16, b_28, &a_4};	/* FD-XREF-CARD-NUM */
static cob_field f_28	= {50, b_28, &a_4};	/* XREF-FILE Record */
static cob_field f_29	= {430, b_32, &a_3};	/* FD-REJS-RECORD */
static cob_field f_32	= {430, b_32, &a_4};	/* DALYREJS-FILE Record */
static cob_field f_33	= {300, b_36, &a_3};	/* FD-ACCTFILE-REC */
static cob_field f_34	= {11, b_36, &a_5};	/* FD-ACCT-ID */
static cob_field f_36	= {300, b_36, &a_4};	/* ACCOUNT-FILE Record */
static cob_field f_37	= {50, b_43, &a_3};	/* FD-TRAN-CAT-BAL-RECORD */
static cob_field f_38	= {17, b_43, &a_3};	/* FD-TRAN-CAT-KEY */
static cob_field f_43	= {50, b_43, &a_4};	/* TCATBAL-FILE Record */
static cob_field f_50	= {11, b_44 + 132, &a_7};	/* DALYTRAN-AMT */
static cob_field f_59	= {2, b_59, &a_3};	/* DALYTRAN-STATUS */
static cob_field f_77	= {2, b_77, &a_3};	/* TRANFILE-STATUS */
static cob_field f_85	= {2, b_85, &a_3};	/* XREFFILE-STATUS */
static cob_field f_88	= {2, b_88, &a_3};	/* DALYREJS-STATUS */
static cob_field f_94	= {12, b_91 + 12, &a_6};	/* ACCT-CURR-BAL */
static cob_field f_95	= {12, b_91 + 24, &a_6};	/* ACCT-CREDIT-LIMIT */
static cob_field f_100	= {12, b_91 + 78, &a_6};	/* ACCT-CURR-CYC-CREDIT */
static cob_field f_101	= {12, b_91 + 90, &a_6};	/* ACCT-CURR-CYC-DEBIT */
static cob_field f_105	= {2, b_105, &a_3};	/* ACCTFILE-STATUS */
static cob_field f_113	= {11, b_108 + 17, &a_7};	/* TRAN-CAT-BAL */
static cob_field f_115	= {2, b_115, &a_3};	/* TCATBALF-STATUS */
static cob_field f_118	= {2, b_118, &a_3};	/* IO-STATUS */
static cob_field f_121	= {2, b_121, &a_10};	/* TWO-BYTES-BINARY */
static cob_field f_125	= {4, b_125, &a_3};	/* IO-STATUS-04 */
static cob_field f_127	= {3, b_125 + 1, &a_11};	/* IO-STATUS-0403 */
static cob_field f_132	= {4, b_132, &a_9};	/* ABCODE */
static cob_field f_133	= {4, b_133, &a_9};	/* TIMING */
static cob_field f_134	= {21, b_134, &a_3};	/* COBOL-TS */
static cob_field f_141	= {2, b_134 + 14, &a_4};	/* COB-MIL */
static cob_field f_157	= {2, b_143 + 20, &a_8};	/* DB2-MIL */
static cob_field f_164	= {76, b_162 + 4, &a_4};	/* WS-VALIDATION-FAIL-REASON-DESC */
static cob_field f_166	= {9, b_165, &a_2};	/* WS-TRANSACTION-COUNT */
static cob_field f_167	= {9, b_165 + 9, &a_2};	/* WS-REJECT-COUNT */
static cob_field f_168	= {11, b_165 + 18, &a_7};	/* WS-TEMP-BAL */

/* End of fields */

