/* Generated by           cobc 3.2.0 */
/* Generated from         <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/complementary-crossarm-v1/run-20260916T112618Z/run/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cbl/CBTRN03C.cbl */
/* Generated at           Sep 16 2026 08:26:20 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -std=ibm -fsign=ascii -I <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/complementary-crossarm-v1/run-20260916T112618Z/run/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cpy -x -C -o <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/complementary-crossarm-v1/run-20260916T112618Z/run/p2b-preparation/isolated-cycle/aws-carddemo-cycle-v1/P2b/build/CBTRN03C.c <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/complementary-crossarm-v1/run-20260916T112618Z/run/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cbl/CBTRN03C.cbl */

/* Program local variables for 'CBTRN03C' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d_0 = NULL;
cob_decimal	*d_1 = NULL;


/* File TRANSACT-FILE */
static cob_file		*h_TRANSACT_FILE = NULL;
static unsigned char	h_TRANSACT_FILE_status[4];

/* File XREF-FILE */
static cob_file_key	*k_XREF_FILE = NULL;
static cob_file		*h_XREF_FILE = NULL;
static unsigned char	h_XREF_FILE_status[4];

/* File TRANTYPE-FILE */
static cob_file_key	*k_TRANTYPE_FILE = NULL;
static cob_file		*h_TRANTYPE_FILE = NULL;
static unsigned char	h_TRANTYPE_FILE_status[4];

/* File TRANCATG-FILE */
static cob_file_key	*k_TRANCATG_FILE = NULL;
static cob_file		*h_TRANCATG_FILE = NULL;
static unsigned char	h_TRANCATG_FILE_status[4];

/* File REPORT-FILE */
static cob_file		*h_REPORT_FILE = NULL;
static unsigned char	h_REPORT_FILE_status[4];

/* File DATE-PARMS-FILE */
static cob_file		*h_DATE_PARMS_FILE = NULL;
static unsigned char	h_DATE_PARMS_FILE_status[4];

/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call pointers */
static cob_call_union	call_CEE3ABD;

/* Call parameters */
cob_field		*cob_procedure_params[2];

/* Perform frame stack */
struct cob_frame	*temp_index;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_21[350] __attribute__((aligned));	/* TRANSACT-FILE Record */
static cob_u8_t	b_25[50] __attribute__((aligned));	/* XREF-FILE Record */
static cob_u8_t	b_29[60] __attribute__((aligned));	/* TRANTYPE-FILE Record */
static cob_u8_t	b_35[60] __attribute__((aligned));	/* TRANCATG-FILE Record */
static cob_u8_t	b_37[133] __attribute__((aligned));	/* REPORT-FILE Record */
static cob_u8_t	b_39[80] __attribute__((aligned));	/* DATE-PARMS-FILE Record */
static cob_u8_t	b_40[350] __attribute__((aligned));	/* TRAN-RECORD */
static cob_u8_t	b_55[2] __attribute__((aligned));	/* TRANFILE-STATUS */
static cob_u8_t	b_58[50] __attribute__((aligned));	/* CARD-XREF-RECORD */
static cob_u8_t	b_63[2] __attribute__((aligned));	/* CARDXREF-STATUS */
static cob_u8_t	b_66[60] __attribute__((aligned));	/* TRAN-TYPE-RECORD */
static cob_u8_t	b_70[2] __attribute__((aligned));	/* TRANTYPE-STATUS */
static cob_u8_t	b_73[60] __attribute__((aligned));	/* TRAN-CAT-RECORD */
static cob_u8_t	b_79[2] __attribute__((aligned));	/* TRANCATG-STATUS */
static cob_u8_t	b_82[115] __attribute__((aligned));	/* REPORT-NAME-HEADER */
static cob_u8_t	b_89[114] __attribute__((aligned));	/* TRANSACTION-DETAIL-REPORT */
static cob_u8_t	b_106[114] __attribute__((aligned));	/* TRANSACTION-HEADER-1 */
static cob_u8_t	b_114[133] __attribute__((aligned));	/* TRANSACTION-HEADER-2 */
static cob_u8_t	b_115[112] __attribute__((aligned));	/* REPORT-PAGE-TOTALS */
static cob_u8_t	b_119[112] __attribute__((aligned));	/* REPORT-ACCOUNT-TOTALS */
static cob_u8_t	b_123[112] __attribute__((aligned));	/* REPORT-GRAND-TOTALS */
static cob_u8_t	b_127[2] __attribute__((aligned));	/* TRANREPT-STATUS */
static cob_u8_t	b_130[2] __attribute__((aligned));	/* DATEPARM-STATUS */
static cob_u8_t	b_133[21] __attribute__((aligned));	/* WS-DATEPARM-RECORD */
static cob_u8_t	b_137[190] __attribute__((aligned));	/* WS-REPORT-VARS */
static cob_u8_t	b_146[2] __attribute__((aligned));	/* IO-STATUS */
static cob_u8_t	b_149[2] __attribute__((aligned));	/* TWO-BYTES-BINARY */
static cob_u8_t	b_153[4] __attribute__((aligned));	/* IO-STATUS-04 */
static cob_u8_t	b_156[4] __attribute__((aligned));	/* APPL-RESULT */
static cob_u8_t	b_159[1] __attribute__((aligned));	/* END-OF-FILE */
static cob_u8_t	b_160[4] __attribute__((aligned));	/* ABCODE */
static cob_u8_t	b_161[4] __attribute__((aligned));	/* TIMING */

/* End of local data storage */


/* Fields (local) */
static cob_field f_21	= {350, b_21, &a_4};	/* TRANSACT-FILE Record */
static cob_field f_23	= {16, b_25, &a_4};	/* FD-XREF-CARD-NUM */
static cob_field f_25	= {50, b_25, &a_4};	/* XREF-FILE Record */
static cob_field f_27	= {2, b_29, &a_4};	/* FD-TRAN-TYPE */
static cob_field f_29	= {60, b_29, &a_4};	/* TRANTYPE-FILE Record */
static cob_field f_31	= {6, b_35, &a_2};	/* FD-TRAN-CAT-KEY */
static cob_field f_35	= {60, b_35, &a_4};	/* TRANCATG-FILE Record */
static cob_field f_36	= {133, b_37, &a_4};	/* FD-REPTFILE-REC */
static cob_field f_37	= {133, b_37, &a_4};	/* REPORT-FILE Record */
static cob_field f_39	= {80, b_39, &a_4};	/* DATE-PARMS-FILE Record */
static cob_field f_40	= {350, b_40, &a_2};	/* TRAN-RECORD */
static cob_field f_46	= {11, b_40 + 132, &a_3};	/* TRAN-AMT */
static cob_field f_55	= {2, b_55, &a_2};	/* TRANFILE-STATUS */
static cob_field f_63	= {2, b_63, &a_2};	/* CARDXREF-STATUS */
static cob_field f_70	= {2, b_70, &a_2};	/* TRANTYPE-STATUS */
static cob_field f_79	= {2, b_79, &a_2};	/* TRANCATG-STATUS */
static cob_field f_82	= {115, b_82, &a_2};	/* REPORT-NAME-HEADER */
static cob_field f_89	= {114, b_89, &a_2};	/* TRANSACTION-DETAIL-REPORT */
static cob_field f_104	= {15, b_89 + 97, &a_9};	/* TRAN-REPORT-AMT */
static cob_field f_106	= {114, b_106, &a_2};	/* TRANSACTION-HEADER-1 */
static cob_field f_115	= {112, b_115, &a_2};	/* REPORT-PAGE-TOTALS */
static cob_field f_118	= {15, b_115 + 97, &a_7};	/* REPT-PAGE-TOTAL */
static cob_field f_119	= {112, b_119, &a_2};	/* REPORT-ACCOUNT-TOTALS */
static cob_field f_122	= {15, b_119 + 97, &a_7};	/* REPT-ACCOUNT-TOTAL */
static cob_field f_123	= {112, b_123, &a_2};	/* REPORT-GRAND-TOTALS */
static cob_field f_126	= {15, b_123 + 97, &a_7};	/* REPT-GRAND-TOTAL */
static cob_field f_127	= {2, b_127, &a_2};	/* TRANREPT-STATUS */
static cob_field f_130	= {2, b_130, &a_2};	/* DATEPARM-STATUS */
static cob_field f_134	= {10, b_133, &a_4};	/* WS-START-DATE */
static cob_field f_136	= {10, b_133 + 11, &a_4};	/* WS-END-DATE */
static cob_field f_139	= {5, b_137 + 1, &a_5};	/* WS-LINE-COUNTER */
static cob_field f_140	= {2, b_137 + 6, &a_6};	/* WS-PAGE-SIZE */
static cob_field f_142	= {11, b_137 + 141, &a_3};	/* WS-PAGE-TOTAL */
static cob_field f_143	= {11, b_137 + 152, &a_3};	/* WS-ACCOUNT-TOTAL */
static cob_field f_144	= {11, b_137 + 163, &a_3};	/* WS-GRAND-TOTAL */
static cob_field f_146	= {2, b_146, &a_2};	/* IO-STATUS */
static cob_field f_149	= {2, b_149, &a_11};	/* TWO-BYTES-BINARY */
static cob_field f_153	= {4, b_153, &a_2};	/* IO-STATUS-04 */
static cob_field f_155	= {3, b_153 + 1, &a_12};	/* IO-STATUS-0403 */
static cob_field f_156	= {4, b_156, &a_10};	/* APPL-RESULT */
static cob_field f_160	= {4, b_160, &a_10};	/* ABCODE */
static cob_field f_161	= {4, b_161, &a_10};	/* TIMING */

/* End of fields */

