/* Generated by           cobc 3.2.0 */
/* Generated from         <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/source-tree/app/cbl/CBACT04C.cbl */
/* Generated at           Sep 15 2026 10:27:37 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        /opt/homebrew/bin/cobc -std=ibm -fsign=ascii -I <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/source-tree/app/cpy -m -C -o <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/instrumented-build/CBACT04C.c <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/source-tree/app/cbl/CBACT04C.cbl */

static cob_u8_t			*cob_parm_157 = NULL;

/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x10,   4,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_3 =	{0x10,   9,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x10,  11,   0, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_7 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_8 =	{0x10,  11,   2, 0x0001, NULL};
static const cob_field_attr a_9 =	{0x10,   6,   2, 0x0001, NULL};
static const cob_field_attr a_10 =	{0x10,  12,   2, 0x0001, NULL};
static const cob_field_attr a_11 =	{0x10,   6,   0, 0x0000, NULL};
static const cob_field_attr a_12 =	{0x10,   2,   0, 0x0000, NULL};
static const cob_field_attr a_13 =	{0x11,   9,   0, 0x0021, NULL};
static const cob_field_attr a_14 =	{0x11,   4,   0, 0x0020, NULL};
static const cob_field_attr a_15 =	{0x10,   3,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {4, (cob_u8_ptr)"1200", &a_1};
static const cob_field c_2	= {38, (cob_u8_ptr)"START OF EXECUTION OF PROGRAM CBACT04C", &a_2};
static const cob_field c_3	= {1, (cob_u8_ptr)"0", &a_7};
static const cob_field c_4	= {36, (cob_u8_ptr)"END OF EXECUTION OF PROGRAM CBACT04C", &a_2};
static const cob_field c_5	= {42, (cob_u8_ptr)"ERROR OPENING TRANSACTION CATEGORY BALANCE", &a_2};
static const cob_field c_6	= {28, (cob_u8_ptr)"ERROR OPENING CROSS REF FILE", &a_2};
static const cob_field c_7	= {31, (cob_u8_ptr)"ERROR OPENING DALY REJECTS FILE", &a_2};
static const cob_field c_8	= {33, (cob_u8_ptr)"ERROR OPENING ACCOUNT MASTER FILE", &a_2};
static const cob_field c_9	= {30, (cob_u8_ptr)"ERROR OPENING TRANSACTION FILE", &a_2};
static const cob_field c_10	= {39, (cob_u8_ptr)"ERROR READING TRANSACTION CATEGORY FILE", &a_2};
static const cob_field c_11	= {29, (cob_u8_ptr)"ERROR RE-WRITING ACCOUNT FILE", &a_2};
static const cob_field c_12	= {19, (cob_u8_ptr)"ACCOUNT NOT FOUND: ", &a_2};
static const cob_field c_13	= {26, (cob_u8_ptr)"ERROR READING ACCOUNT FILE", &a_2};
static const cob_field c_14	= {23, (cob_u8_ptr)"ERROR READING XREF FILE", &a_2};
static const cob_field c_15	= {31, (cob_u8_ptr)"DISCLOSURE GROUP RECORD MISSING", &a_2};
static const cob_field c_16	= {27, (cob_u8_ptr)"TRY WITH DEFAULT GROUP CODE", &a_2};
static const cob_field c_17	= {35, (cob_u8_ptr)"ERROR READING DISCLOSURE GROUP FILE", &a_2};
static const cob_field c_18	= {38, (cob_u8_ptr)"ERROR READING DEFAULT DISCLOSURE GROUP", &a_2};
static const cob_field c_19	= {13, (cob_u8_ptr)"Int. for a/c ", &a_2};
static const cob_field c_20	= {32, (cob_u8_ptr)"ERROR WRITING TRANSACTION RECORD", &a_2};
static const cob_field c_21	= {38, (cob_u8_ptr)"ERROR CLOSING TRANSACTION BALANCE FILE", &a_2};
static const cob_field c_22	= {28, (cob_u8_ptr)"ERROR CLOSING CROSS REF FILE", &a_2};
static const cob_field c_23	= {35, (cob_u8_ptr)"ERROR CLOSING DISCLOSURE GROUP FILE", &a_2};
static const cob_field c_24	= {26, (cob_u8_ptr)"ERROR CLOSING ACCOUNT FILE", &a_2};
static const cob_field c_25	= {30, (cob_u8_ptr)"ERROR CLOSING TRANSACTION FILE", &a_2};
static const cob_field c_26	= {16, (cob_u8_ptr)"ABENDING PROGRAM", &a_2};
static const cob_field c_27	= {20, (cob_u8_ptr)"FILE STATUS IS: NNNN", &a_2};
static const cob_field c_28	= {8, (cob_u8_ptr)"TCATBALF", &a_2};
static const cob_field c_29	= {8, (cob_u8_ptr)"XREFFILE", &a_2};
static const cob_field c_30	= {8, (cob_u8_ptr)"ACCTFILE", &a_2};
static const cob_field c_31	= {7, (cob_u8_ptr)"DISCGRP", &a_2};
static const cob_field c_32	= {8, (cob_u8_ptr)"TRANSACT", &a_2};


static COB_INLINE COB_A_INLINE int
cob_cmpswp_s32 (const void *p, const cob_s64_t n)
{
	int	val;
	void	*x;
	x = &val;
	optim_memcpy (x, p, 4);
	val = COB_BSWAP_32 (val);
	return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE void
cob_setswp_s32 (void *p, const int val)
{
	int		n;
	unsigned char		*x;
	unsigned char		*px = p;
	n = val;
	x = (unsigned char *)&n;
	px[0] = x[3];
	px[1] = x[2];
	px[2] = x[1];
	px[3] = x[0];
}


/* Decimal constants */
static	cob_decimal	kc_1;
static	cob_decimal	*dc_1 = NULL;

