/* Generated by           cobc 3.2.0 */
/* Generated from         <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/interrupted/flush_probe.cbl */
/* Generated at           Sep 15 2026 10:27:40 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        /opt/homebrew/bin/cobc -std=ibm -fsign=ascii -I <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/interrupted -x -free -C -o <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/interrupted/flush_probe.c <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/interrupted/flush_probe.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x11,   9,   0, 0x0041, NULL};


/* Constants */
static const cob_field c_1	= {17, (cob_u8_ptr)"FLUSH-PROBE-READY", &a_1};
static const cob_field c_2	= {22, (cob_u8_ptr)"FLUSH-PROBE-NORMAL-END", &a_1};

