/* Generated by           cobc 3.2.0 */
/* Generated from         <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/complementary-crossarm-v1/run-20260916T112642Z/run/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cbl/CBTRN02C.cbl */
/* Generated at           Sep 16 2026 08:26:43 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -std=ibm -fsign=ascii -I <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/complementary-crossarm-v1/run-20260916T112642Z/run/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cpy -x -A -Dcob_write=p2b_observed_write -C -o <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/complementary-crossarm-v1/run-20260916T112642Z/run/p2b-preparation/isolated-cycle/aws-carddemo-cycle-v1/P2b/build/CBTRN02C.c <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/complementary-crossarm-v1/run-20260916T112642Z/run/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cbl/CBTRN02C.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   9,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x10,  11,   0, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x10,  12,   2, 0x0001, NULL};
static const cob_field_attr a_7 =	{0x10,  11,   2, 0x0001, NULL};
static const cob_field_attr a_8 =	{0x10,   2,   0, 0x0000, NULL};
static const cob_field_attr a_9 =	{0x11,   9,   0, 0x0021, NULL};
static const cob_field_attr a_10 =	{0x11,   4,   0, 0x0020, NULL};
static const cob_field_attr a_11 =	{0x10,   3,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {38, (cob_u8_ptr)"START OF EXECUTION OF PROGRAM CBTRN02C", &a_1};
static const cob_field c_2	= {24, (cob_u8_ptr)"TRANSACTIONS PROCESSED :", &a_1};
static const cob_field c_3	= {24, (cob_u8_ptr)"TRANSACTIONS REJECTED  :", &a_1};
static const cob_field c_4	= {36, (cob_u8_ptr)"END OF EXECUTION OF PROGRAM CBTRN02C", &a_1};
static const cob_field c_5	= {22, (cob_u8_ptr)"ERROR OPENING DALYTRAN", &a_1};
static const cob_field c_6	= {30, (cob_u8_ptr)"ERROR OPENING TRANSACTION FILE", &a_1};
static const cob_field c_7	= {28, (cob_u8_ptr)"ERROR OPENING CROSS REF FILE", &a_1};
static const cob_field c_8	= {31, (cob_u8_ptr)"ERROR OPENING DALY REJECTS FILE", &a_1};
static const cob_field c_9	= {33, (cob_u8_ptr)"ERROR OPENING ACCOUNT MASTER FILE", &a_1};
static const cob_field c_10	= {38, (cob_u8_ptr)"ERROR OPENING TRANSACTION BALANCE FILE", &a_1};
static const cob_field c_11	= {27, (cob_u8_ptr)"ERROR READING DALYTRAN FILE", &a_1};
static const cob_field c_12	= {25, (cob_u8_ptr)"INVALID CARD NUMBER FOUND", &a_1};
static const cob_field c_13	= {24, (cob_u8_ptr)"ACCOUNT RECORD NOT FOUND", &a_1};
static const cob_field c_14	= {21, (cob_u8_ptr)"OVERLIMIT TRANSACTION", &a_1};
static const cob_field c_15	= {42, (cob_u8_ptr)"TRANSACTION RECEIVED AFTER ACCT EXPIRATION", &a_1};
static const cob_field c_16	= {29, (cob_u8_ptr)"ERROR WRITING TO REJECTS FILE", &a_1};
static const cob_field c_17	= {35, (cob_u8_ptr)"TCATBAL record not found for key : ", &a_1};
static const cob_field c_18	= {12, (cob_u8_ptr)".. Creating.", &a_1};
static const cob_field c_19	= {38, (cob_u8_ptr)"ERROR READING TRANSACTION BALANCE FILE", &a_1};
static const cob_field c_20	= {38, (cob_u8_ptr)"ERROR WRITING TRANSACTION BALANCE FILE", &a_1};
static const cob_field c_21	= {40, (cob_u8_ptr)"ERROR REWRITING TRANSACTION BALANCE FILE", &a_1};
static const cob_field c_22	= {33, (cob_u8_ptr)"ERROR WRITING TO TRANSACTION FILE", &a_1};
static const cob_field c_23	= {27, (cob_u8_ptr)"ERROR CLOSING DALYTRAN FILE", &a_1};
static const cob_field c_24	= {30, (cob_u8_ptr)"ERROR CLOSING TRANSACTION FILE", &a_1};
static const cob_field c_25	= {28, (cob_u8_ptr)"ERROR CLOSING CROSS REF FILE", &a_1};
static const cob_field c_26	= {32, (cob_u8_ptr)"ERROR CLOSING DAILY REJECTS FILE", &a_1};
static const cob_field c_27	= {26, (cob_u8_ptr)"ERROR CLOSING ACCOUNT FILE", &a_1};
static const cob_field c_28	= {38, (cob_u8_ptr)"ERROR CLOSING TRANSACTION BALANCE FILE", &a_1};
static const cob_field c_29	= {16, (cob_u8_ptr)"ABENDING PROGRAM", &a_1};
static const cob_field c_30	= {20, (cob_u8_ptr)"FILE STATUS IS: NNNN", &a_1};
static const cob_field c_31	= {8, (cob_u8_ptr)"DALYTRAN", &a_1};
static const cob_field c_32	= {8, (cob_u8_ptr)"TRANFILE", &a_1};
static const cob_field c_33	= {8, (cob_u8_ptr)"XREFFILE", &a_1};
static const cob_field c_34	= {8, (cob_u8_ptr)"DALYREJS", &a_1};
static const cob_field c_35	= {8, (cob_u8_ptr)"ACCTFILE", &a_1};
static const cob_field c_36	= {8, (cob_u8_ptr)"TCATBALF", &a_1};


static COB_INLINE COB_A_INLINE int
cob_cmpswp_s32 (const void *p, const cob_s64_t n)
{
	int	val;
	void	*x;
	x = &val;
	optim_memcpy (x, p, 4);
	val = COB_BSWAP_32 (val);
	return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE void
cob_setswp_s32 (void *p, const int val)
{
	int		n;
	unsigned char		*x;
	unsigned char		*px = p;
	n = val;
	x = (unsigned char *)&n;
	px[0] = x[3];
	px[1] = x[2];
	px[2] = x[1];
	px[3] = x[0];
}

