/* Generated by           cobc 3.2.0 */
/* Generated from         <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/complementary-crossarm-v1/run-20260916T112642Z/run/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cbl/CBTRN03C.cbl */
/* Generated at           Sep 16 2026 08:26:44 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -std=ibm -fsign=ascii -I <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/complementary-crossarm-v1/run-20260916T112642Z/run/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cpy -x -C -o <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/complementary-crossarm-v1/run-20260916T112642Z/run/p2b-preparation/isolated-cycle/aws-carddemo-cycle-v1/P2b/build/CBTRN03C.c <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/complementary-crossarm-v1/run-20260916T112642Z/run/p2b-preparation/isolated-cycle/aws-carddemo-preparation/research-corpus/app/cbl/CBTRN03C.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
	{'+', 1},
	{'Z', 3},
	{',', 1},
	{'Z', 3},
	{',', 1},
	{'Z', 3},
	{'.', 1},
	{'Z', 2},
	{'\0', 1}
};
static const cob_pic_symbol p_2[] = {
	{'-', 1},
	{'Z', 3},
	{',', 1},
	{'Z', 3},
	{',', 1},
	{'Z', 3},
	{'.', 1},
	{'Z', 2},
	{'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,  11,   2, 0x0001, NULL};
static const cob_field_attr a_4 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x12,   9,   0, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x12,   3,   0, 0x0000, NULL};
static const cob_field_attr a_7 =	{0x24,  11,   2, 0x0001, p_1};
static const cob_field_attr a_8 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_9 =	{0x24,  11,   2, 0x0001, p_2};
static const cob_field_attr a_10 =	{0x11,   9,   0, 0x0021, NULL};
static const cob_field_attr a_11 =	{0x11,   4,   0, 0x0020, NULL};
static const cob_field_attr a_12 =	{0x10,   3,   0, 0x0000, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1	= {38, (cob_u8_ptr)"START OF EXECUTION OF PROGRAM CBTRN03C", &a_1};
static const cob_field c_2	= {9, (cob_u8_ptr)"TRAN-AMT ", &a_1};
static const cob_field c_3	= {13, (cob_u8_ptr)"WS-PAGE-TOTAL", &a_1};
static const cob_field c_4	= {36, (cob_u8_ptr)"END OF EXECUTION OF PROGRAM CBTRN03C", &a_1};
static const cob_field c_5	= {15, (cob_u8_ptr)"Reporting from ", &a_1};
static const cob_field c_6	= {4, (cob_u8_ptr)" to ", &a_1};
static const cob_field c_7	= {27, (cob_u8_ptr)"ERROR READING DATEPARM FILE", &a_1};
static const cob_field c_8	= {30, (cob_u8_ptr)"ERROR READING TRANSACTION FILE", &a_1};
static const cob_field c_9	= {1, (cob_u8_ptr)"0", &a_8};
static const cob_field c_10	= {22, (cob_u8_ptr)"ERROR WRITING REPTFILE", &a_1};
static const cob_field c_11	= {22, (cob_u8_ptr)"ERROR OPENING TRANFILE", &a_1};
static const cob_field c_12	= {22, (cob_u8_ptr)"ERROR OPENING REPTFILE", &a_1};
static const cob_field c_13	= {28, (cob_u8_ptr)"ERROR OPENING CROSS REF FILE", &a_1};
static const cob_field c_14	= {35, (cob_u8_ptr)"ERROR OPENING TRANSACTION TYPE FILE", &a_1};
static const cob_field c_15	= {35, (cob_u8_ptr)"ERROR OPENING TRANSACTION CATG FILE", &a_1};
static const cob_field c_16	= {28, (cob_u8_ptr)"ERROR OPENING DATE PARM FILE", &a_1};
static const cob_field c_17	= {22, (cob_u8_ptr)"INVALID CARD NUMBER : ", &a_1};
static const cob_field c_18	= {27, (cob_u8_ptr)"INVALID TRANSACTION TYPE : ", &a_1};
static const cob_field c_19	= {24, (cob_u8_ptr)"INVALID TRAN CATG KEY : ", &a_1};
static const cob_field c_20	= {37, (cob_u8_ptr)"ERROR CLOSING POSTED TRANSACTION FILE", &a_1};
static const cob_field c_21	= {25, (cob_u8_ptr)"ERROR CLOSING REPORT FILE", &a_1};
static const cob_field c_22	= {28, (cob_u8_ptr)"ERROR CLOSING CROSS REF FILE", &a_1};
static const cob_field c_23	= {35, (cob_u8_ptr)"ERROR CLOSING TRANSACTION TYPE FILE", &a_1};
static const cob_field c_24	= {35, (cob_u8_ptr)"ERROR CLOSING TRANSACTION CATG FILE", &a_1};
static const cob_field c_25	= {28, (cob_u8_ptr)"ERROR CLOSING DATE PARM FILE", &a_1};
static const cob_field c_26	= {16, (cob_u8_ptr)"ABENDING PROGRAM", &a_1};
static const cob_field c_27	= {20, (cob_u8_ptr)"FILE STATUS IS: NNNN", &a_1};
static const cob_field c_28	= {8, (cob_u8_ptr)"TRANFILE", &a_1};
static const cob_field c_29	= {8, (cob_u8_ptr)"CARDXREF", &a_1};
static const cob_field c_30	= {8, (cob_u8_ptr)"TRANTYPE", &a_1};
static const cob_field c_31	= {8, (cob_u8_ptr)"TRANCATG", &a_1};
static const cob_field c_32	= {8, (cob_u8_ptr)"TRANREPT", &a_1};
static const cob_field c_33	= {8, (cob_u8_ptr)"DATEPARM", &a_1};

static cob_field cob_all_zero	= {1, (cob_u8_ptr)"0", &cob_all_attr};


static int COB_NOINLINE
cob_add_packed_int (cob_field *f, const int val)
{
	register unsigned char	*p;
	size_t		size;
	int		carry = 0;
	int		n;
	int		inc;
	if (val == 0) {
		return 0;
	}
	p = f->data + f->size - 1;
	if ((*p & 0x0f) == 0x0d) {
		if (val > 0) {
			return cob_add_int (f, val, 0);
		}
		n = -val;
	} else {
		if (val < 0) {
			return cob_add_int (f, val, 0);
		}
		n = val;
	}
	inc = (*p >> 4) + (n % 10);
	n /= 10;
	carry = inc / 10;
	*p = ((inc % 10) << 4) | (*p & 0x0f);
	p--;
	for (size = 0; size < f->size - 1; ++size, --p) {
		if (!carry && !n) {
			break;
		}
		inc = ((*p >> 4) * 10) + (*p & 0x0f) + carry + (n % 100);
		carry = inc / 100;
		n /= 100;
		inc %= 100;
		*p = ((inc / 10) << 4) | (inc % 10);
	}
	return 0;
}


static COB_INLINE COB_A_INLINE int
cob_cmpswp_s32 (const void *p, const cob_s64_t n)
{
	int	val;
	void	*x;
	x = &val;
	optim_memcpy (x, p, 4);
	val = COB_BSWAP_32 (val);
	return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE void
cob_subswp_s32 (void *p, const int val)
{
	int		n;
	unsigned char	*x;
	unsigned char	*px = p;
	x = (unsigned char *)&n;
	x[0] = px[3];
	x[1] = px[2];
	x[2] = px[1];
	x[3] = px[0];
	n -= val;
	px[0] = x[3];
	px[1] = x[2];
	px[2] = x[1];
	px[3] = x[0];
}


static COB_INLINE COB_A_INLINE void
cob_setswp_s32 (void *p, const int val)
{
	int		n;
	unsigned char		*x;
	unsigned char		*px = p;
	n = val;
	x = (unsigned char *)&n;
	px[0] = x[3];
	px[1] = x[2];
	px[2] = x[1];
	px[3] = x[0];
}

