/* Generated by           cobc 3.2.0 */
/* Generated from         <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/normal/flush_probe.cbl */
/* Generated at           Sep 15 2026 10:27:37 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        /opt/homebrew/bin/cobc -std=ibm -fsign=ascii -I <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/normal -x -free -C -o <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/normal/flush_probe.c <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/normal/flush_probe.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"<REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/normal/flush_probe.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 15 2026 10:27:37"
#define  COB_MODULE_DATE		20260915
#define  COB_MODULE_TIME		102737

/* Global variables */
#include "flush_probe.c.h"

/* Function prototypes */

static int		FLUSHPROBE ();
static int		FLUSHPROBE_ (const int);
static void		FLUSHPROBE_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (FLUSHPROBE ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'FLUSHPROBE' */

/* ENTRY 'FLUSHPROBE' */

static int
FLUSHPROBE ()
{
  return FLUSHPROBE_ (0);
}

static int
FLUSHPROBE_ (const int entry)
{
  /* Program local variables */
  #include "flush_probe.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 7         : Entry     FLUSHPROBE              : <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/normal/flush_probe.cbl */
  l_2:;

  /* Line: 7         : DISPLAY            : <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/normal/flush_probe.cbl */
  cob_display (0, 1, 1, &c_1);

  /* Line: 8         : CALL               : <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/normal/flush_probe.cbl */
  cob_procedure_params[0] = &f_17;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_technical_sleep_seconds.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
  {
    call_technical_sleep_seconds.funcvoid = cob_resolve_cobol ("technical_sleep_seconds", 0, 1);
  }
  b_2 = ((int (*)(void *))call_technical_sleep_seconds.funcint) (b_17);

  /* Line: 9         : DISPLAY            : <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/normal/flush_probe.cbl */
  cob_display (0, 1, 1, &c_2);

  /* Line: 10        : STOP RUN           : <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/normal/flush_probe.cbl */
  cob_stop_run (b_2);

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  FLUSHPROBE_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE, Default byte: 0x00 */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field sleep-seconds */
  (*(int *)(b_17)) = 2;


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'FLUSHPROBE' */

/* Initialize module structure for FLUSHPROBE */
static void FLUSHPROBE_module_init (cob_module *module)
{
  module->module_name = "FLUSHPROBE";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())FLUSHPROBE;
  module->module_cancel.funcptr = (void *(*)())FLUSHPROBE_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 0;
  module->flag_pretty_display = 0;
  module->flag_host_sign = 1;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

