/* Generated by           cobc 3.2.0 */
/* Generated from         <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/normal/flush_probe.cbl */
/* Generated at           Sep 15 2026 10:27:37 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        /opt/homebrew/bin/cobc -std=ibm -fsign=ascii -I <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/normal -x -free -C -o <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/normal/flush_probe.c <REDACTED_LOCAL_PATH>/casos/aws-carddemo-cycle-v1/P3/coverage-prequalification-v1/evidence-20260915Tprequal-v1/synthetic-flush-probe/normal/flush_probe.cbl */

/* Program local variables for 'FLUSHPROBE' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call pointers */
static cob_call_union	call_technical_sleep_seconds;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*temp_index;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[4] __attribute__((aligned));	/* sleep-seconds */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {4, b_17, &a_2};	/* sleep-seconds */

/* End of fields */

